/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Menu: typeof import('./src/components/Menu/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TButton: typeof import('tdesign-vue-next')['Button']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TMenu: typeof import('tdesign-vue-next')['Menu']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
    TSubmenu: typeof import('tdesign-vue-next')['Submenu']
    TUpload: typeof import('tdesign-vue-next')['Upload']
    UploadImg: typeof import('./src/components/UploadImg/index.vue')['default']
  }
}
